#!/bin/bash
cd
sudo apt update
sudo apt upgrade -y
curl -sSL https://get.docker.com | sh

sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker

sudo apt install -y libffi-dev libssl-dev python3-pip
sudo pip3 install docker-compose
