#!/bin/bash

#Actualizar LinuxMint.
sudo apt update && sudo apt upgrade -y

#Instalar paquetes requeridos.
sudo apt install software-properties-common apt-transport-https wget -y

#Importar repositorio de código de Visual Studio
sudo wget -O- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/vscode.gpg
echo deb [arch=amd64 signed-by=/usr/share/keyrings/vscode.gpg] https://packages.microsoft.com/repos/vscode stable main | sudo tee /etc/apt/sources.list.d/vscode.list

#Instalar Visual Studio
sudo apt update
sudo apt install code -y

