#!/bin/bash

#Actualizar repositorios y paquetería instalada:
sudo apt-get update && sudo apt-get upgrade

#Instalamos lo necesario para pip3:
sudo apt-get install libffi-dev libssl-dev python3-dev python3 python3-pip

#Descargar e instalar lo necesario para docker:
curl -sSL https://get.docker.com | sh

#Habilitar al usuario actual para ejecutar docker:
sudo usermod -aG docker ${USER}
sudo reboot